# Site settings
title: Floating Boy, LLC
email: shawn@floatingboy.org
description: > # this means to ignore newlines until "baseurl:"
  For Reference Only
baseurl: "" # the subpath of your site, e.g. /blog/
tag_line: For Reference Only
url: "https://floatingboy.org" # the base hostname & protocol for your site
domain: floatingboy.org
repository: wrenchpilot/floatingboy.org
full_name: James Shawn Carnley
linkedin_username: shawncarnley
github_username: wrenchpilot

# Build settings
markdown: kramdown

paginate: 20
paginate_path: "/blog/page:num/"

github: [metadata]

measurement_id: G-3PQD8PZ0TN
airbnb_id: 30394346

plugins:
  - jekyll-avatar
  - jekyll-feed